### ISSUE TITLE
Login authentication issue of token  403 error

### ISSUE THREAD

**Issue by chitranjan17** [ddo/oauth-1.0a#103]
**Hi I am using oath plugin in our ionic 1 app  but getting Login authentication issue of invalid attempt  403 while validating with Netsuite Server . As authorisation header  some time not  generated proper in some of  android  device  as attach in the screen shots. Please help Me to  fixed this issue or what could be possible reason for it.**

![EC 028-A Chollamuthu](https://user-images.githubusercontent.com/34195490/107612470-57308f00-6c6c-11eb-9ac4-6f06763355c5.jpg)
![EC 066-Punitha](https://user-images.githubusercontent.com/34195490/107612474-58fa5280-6c6c-11eb-9a43-068c9d71d746.jpg)
![EC 093 Ayisha](https://user-images.githubusercontent.com/34195490/107612476-5992e900-6c6c-11eb-82da-0d70bc8588b3.jpg)
![EC-068 M Subbulakshmi](https://user-images.githubusercontent.com/34195490/107612477-5a2b7f80-6c6c-11eb-9dcd-2377b6444b04.jpg)
![EC-109 Radha](https://user-images.githubusercontent.com/34195490/107612478-5ac41600-6c6c-11eb-9f45-a02e139cfadb.jpg)
![EC-340-Albin](https://user-images.githubusercontent.com/34195490/107612479-5b5cac80-6c6c-11eb-8419-dc2319f64960.jpg)

**Comment by serberm** [comment]
any update on this? I'm having same issue with Netsuite, in Postman it works fine.

**Comment by AxayDixit** [comment]
@chitranjan17 & @Serber92 have you guys found any solution for this? I'm also stuck at this(using react native). Please let me know.

**Comment by ddo** [comment]
please show the code

**Comment by AxayDixit** [comment]
@ddo hey, thanks for the response. Please have a look at the below code:

`const Crypto = require('crypto-js');`
`const OAuth = require('oauth-1.0a')`

`const oauth = OAuth({
    consumer: {
        key: 'MY_KEY',
        secret: 'MY_SECRET_KEY',
    },
    signature_method: 'HMAC-SHA256',
    hash_function(base_string, key) {
        return Crypto.HmacSHA256(base_string, key).toString(CryptoJS.enc.Base64)
    },
})`

`const request_data = {
    url: 'URL',
    method: 'POST',
    // data: { status: 'Hello Ladies + Gentlemen, a signed OAuth request!' },
}`

// Note: The token is optional for some requests
`const token = {
    key: 'MY_TOKEN_KEY,
    secret: 'MY_TOKEN_SECRET',
}`

`fetch('URL', {
  method: 'POST',
  headers: oauth.toHeader(oauth.authorize(request_data, token)),
}).then((response) => {response.json())
    .then((responseJson) => {})
    .catch((error) => {});`

But i'm getting 401 status from the API.

I also tried using "react-native-crypto" to generate signture but, it is throwing errors related to the package and shim file(even after importing it in the code). Please let me know the correct way, if I'm missing out something.

**Comment by chitranjan17** [comment]
> @chitranjan17 & @Serber92 have you guys found any solution for this? I'm also stuck at this(using react native). Please let me know.

Please check with the time zone  you are appending with the request if it not match with  NS  server  you get this error.

**Comment by chitranjan17** [comment]
> any update on this? I'm having same issue with Netsuite, in Postman it works fine.

Please check with the time zone you are appending with the request if it not match with NS server you get this error.

**Comment by chitranjan17** [comment]
I have this issue of time zone mismatch , so it resolve in my case

**Comment by ddo** [comment]
@chitranjan17 thanks

**Comment by AxayDixit** [comment]
> > @chitranjan17 & @Serber92 have you guys found any solution for this? I'm also stuck at this(using react native). Please let me know.
> 
> Please check with the time zone you are appending with the request if it not match with NS server you get this error.

@chitranjan17 hey, using **oauth-1.0a** the authorization parameters are generated by the library itself including the timestamp. So, if I switch to **crypto-js** then I can create all the necessary autorization parameters from my end in which case I'm creating timestamp like this(in EST):
        `var timeZoneOffset = 300; // Eastern Standard Time`
        `var sameDate = (new Date(((new Date()) - (timeZoneOffset * 60 * 1000)))).toISOString()`
        `let timestamp = new Date(sameDate).getTime()`

But, still the NS server is throwing **400 status**. 

Can you please provide me a working example of this?

**Comment by chitranjan17** [comment]
Will you please check with the mobile setting what time zone you are using?
may be this mismatch with NS time zone.
