### ISSUE TITLE
Authorized request example?

### ISSUE THREAD

**Issue by svinqvmraka** [ddo/oauth-1.0a#12]
Hi, I'm using your library(with jQuery.ajax in the browser) to authenticate with a wordpress site(WP-API; the client and the site are on the same domain, different directories) and I've done the authentication part up to the point where I get the oauth_token and oauth_token_secret. My problem is that I'm not really sure how to make the authenticated request that actually gets the protected resources - I seem to always get a json_not_logged_in error. Is that something this library can handle or I should use something else? I checked out "oauth-request" but I'm not sure how to use it without node.js. Any help would be super appreciated!

**Comment by ddo** [comment]
I don't have any testing website so it's kinda hard

* Did oauth-request work ?
* Did you pass 3 steps ? since ``json_not_logged_in`` means you are not authenticated yet

**Comment by svinqvmraka** [comment]
* I'm working from the browser and I don't really know how to use oauth-request without node.js

* Yes, I did. I'm getting the oauth_token and oauth_token_secret successfully, but when making the request to the protected resources(in the case of wp-api - a test GET request to site.com/wp-json/users/me), I'm getting a json_not_logged_in. I'm not sure what else I'm supposed to do. This could be a problem with WP-API or (most probably) something I'm not doing right, so feel free to close this if you think it's not related to your library.

**Comment by jaschaio** [comment]
For anybody having this same problem. It wasn't quite clear to me that the second parameter `token` passed to `oauth.authorize` was ment to be an object composed of:

```
var token = {
    key: oauth_token,
    secret: oauth_token_secret
}
```

If passing it that way I don't any longer get `not authorized` errors from the API
