### ISSUE TITLE
no support for oauth_callback

### ISSUE THREAD

**Issue by alexzm1** [ddo/oauth-1.0a#14]
This client doesn't support the oauth_callback attribute required in the [get request token authentication step.](http://oauthbible.com/#oauth-10a-three-legged)

**Comment by alexzm1** [comment]
I just found that this was addressed in this [Pull Request] (https://github.com/ddo/oauth-1.0a/pull/3)

**Comment by ddo** [comment]
You can send any data as you want with the data option, not just only your custom attribute but oauth stuff also (i keep make this client simple and flexible)

Take a look on my bitbucket testing

```js
var request_data = {
    url: 'https://bitbucket.org/api/1.0/oauth/request_token',
    method: 'POST',
    data: {
        oauth_callback: 'http://www.ddo.me'
    }
};
```

Call a request

```js
request({
    url: request_data.url,
    method: request_data.method,
    form: oauth.authorize(request_data, token)
}, function(error, response, body) {
    //process your data here
});
```

or jQuery

```js
$.ajax({
    url: request_data.url,
    type: request_data.method,
    data: oauth.authorize(request_data, token)
}).done(function(data) {
    //process your data here
});
```

**Comment by ddo** [comment]
i just update the document as well :+1: 

https://github.com/ddo/oauth-1.0a#authorize-options-

**Comment by alexzm1** [comment]
Thanks for that!
