### ISSUE TITLE
When sending "json" body with "request", serialization is needed

### ISSUE THREAD

**Issue by paulrutter** [ddo/oauth-1.0a#19]
Please state in the documentation that when using the ["request"](https://github.com/request/request#requestoptions-callback) module to do a "json" PUT/POST call, the data used for signing should be serialized (by calling JSON.stringify(dataToSign)).
Took me quite a while to figure this out.
Thanks in advance, great stuff nonetheless.

**Comment by ddo** [comment]
ty
