### ISSUE TITLE
Validate existing oauth signature

### ISSUE THREAD

**Issue by ollycox** [ddo/oauth-1.0a#20]
I have the requirement to validate an oauth signature, I've had a look through the module but couldn't see a way to do this.

I've identified a couple of changes that would support this feature but wanted to check if this was already possible.

**Comment by ddo** [comment]
if you want it for testing you can override some methods like what i did here
https://github.com/ddo/oauth-1.0a/blob/master/test/twitter_sample_data.js#L20-L28

**Comment by olivercox** [comment]
No it's not for testing it for validating the signature on an incoming requests  so overriding the methods won't do it.

The use case is signing outgoing requests and then validating the signature of an incoming callback request with the same client and secret.
