### ISSUE TITLE
Example for bitbucket

### ISSUE THREAD

**Issue by jrm2k6** [ddo/oauth-1.0a#25]
It seems that I cannot get a request_token for bitbucket oauth1.
I tried to follow their documentation and the example you have for Etsy but it is still complaining about the oauth_callback missing. 
Do you have any example targeting the bitbucket api?

**Comment by ddo** [comment]
just pass the callback url then will be ok i guess

example:
```js
var request_data = {
    url: 'API_ENDPOINT',
    method: 'POST',
    data: {
        oauth_callback: 'ANY_CALLBACK_URL'
    }
};
```
