### ISSUE TITLE
Invalid Signature - provided signature does not match

### ISSUE THREAD

**Issue by samarthagarwal** [ddo/oauth-1.0a#33]
Here is my code. I am trying my angularJS app to interact with the Woocommerce API over HTTP (NOT HTTPS).

`var oauth = OAuth({
      consumer:{
        public: ck,
        secret: cs
      },
      signature_method: 'HMAC-SHA1',
      last_ampersand: false
    });

    var request_data = {
      url: url,
      method: 'GET'
    };

    var token = {
      public: '370773112-GmHxMAgYyLbNEtIKZeRNFsMKPR9EyMZeS9weJAEb',
      secret: 'LswwdoUaIvS8ltyTt5jkRh4J50vUPVVHtR2YPi5kE'
    };

    $http({
      url: request_data.url,
      method: request_data.method,
      params: oauth.authorize(request_data, token)
    }).then(function(data){
      console.log(data);
    }, function(error){
      console.log(error);
    })`

I always get the following error.

`
errors: [
{
code: "woocommerce_api_authentication_error",
message: "Invalid Signature - provided signature does not match"
}
]`

Any help is highly appreciated.

**Comment by ddo** [comment]
did you try this one https://www.npmjs.com/package/woocommerce-api

**Comment by samarthagarwal** [comment]
Yes, using this for now. But I have issues using this in my client application.


Thanks for your mail.


Sent by Outlook for Android






On Thu, Feb 11, 2016 at 1:14 PM -0800, "Ddo" <notifications@github.com> wrote:





did you try this one https://www.npmjs.com/package/woocommerce-api

---

**Comment by jonathanbarton** [comment]
This issue still exists - the signature is not being calculated correctly

**Comment by nursahketene** [comment]
Hi, I have the issue with 'OAuth signature does not match' error. I am using WP REST API on the server side and I am using node.js on the client side. 

`
    const oauth = OAuth({
      consumer: {
        public: 'some_token',
        secret: 'some_secret',
      }
    });

    const accessUlr = url + '?oauth_verifier=' + authVerifier;
    const request_data = {
      url: accessUlr,
      method: 'POST',
      data: {
        oauth_token: tempAuthToken,
        oauth_secret: tempAuthSecret,
        oauth_callback: 'http://0.0.0.0:3000'
      }
    };
    request({
      url: request_data.url,
      method: request_data.method,
      data: request_data.data,
      headers: oauth.toHeader(oauth.authorize(request_data))
    }, function(error, response, body) {
      if (error) {
        // some code
      }
      else {
        // some code
      }
    });
`

**Comment by PavlosIsaris** [comment]
Why is this topic closed? Was it resolved?

**Comment by nursahketene** [comment]
Yes. this is weird. I don't know if you have resolved it or not!

**Comment by cacpmw** [comment]
I am getting Invalid Signature - provided signature does not match.

I have no Idea why this is happening. I use the same cs & ck on insomnia and it works...


```typescript
import { Request } from "express";
import crypto from 'crypto';

import IOAuth1Provider from "../interfaces/IOAuth1Provider";
import OAuth from "oauth-1.0a";

export default class OAuth1Provider implements IOAuth1Provider {
    oauth: OAuth;

    constructor() {
        this.oauth = new OAuth({
            consumer: { key: `${process.env.WP_CONSUMER_KEY}`, secret: `${process.env.WP_CONSUMER_SECRET}` },
            signature_method: 'HMAC-SHA1',
            hash_function(base_string, key) {
                return crypto
                    .createHmac('sha1', key)
                    .update(base_string)
                    .digest('base64')
            },
        })
    }
    makeHeader(request: Request): OAuth.Header {
        return this.oauth.toHeader(this.oauth.authorize(request));
    }

}
```
