### ISSUE TITLE
Reducing lib size

### ISSUE THREAD

**Issue by crm416** [ddo/oauth-1.0a#37]
Thanks for open-sourcing this--really useful stuff.

I'm noticing that while unminified `oauth-1.0a.js` is just 7 KB, including this library in my minified Webpack bundle adds 60 KB in total to the bundle size. This is almost entirely due to the transitive dependency on CryptoJS.

Would there be any interest in either carving our a smaller crypto dependency (`oauth-1.0a.js` only uses three functions from CryptoJS) or providing a means by which to inject the crypto dependency such that clients could package their own smaller crypto libraries?

Cheers.

**Comment by thisconnect** [comment]
Related https://github.com/brix/crypto-js/issues/60

**Comment by ddo** [comment]
a PR is welcome

**Comment by ddo** [comment]
https://github.com/ddo/oauth-1.0a/releases/tag/2.0.0

**Comment by thisconnect** [comment]
Thanks!!
