### ISSUE TITLE
RSA-SHA1 support

### ISSUE THREAD

**Issue by simonaberry** [ddo/oauth-1.0a#40]
What is the timeframe for RSA-SHA1 support ? I see the code says 'Coming Soon...' ..?

Anything we can do to help/contribute ?

**Comment by simonaberry** [comment]
for anyone who is looking for a quick and nasty solution that works on a nodejs server (i.e. this is not a pure javascript implementation like the rest of this library)

    case 'RSA-SHA1':
			this.hash = function (base_string, key) {
				var sign = crypto.createSign('RSA-SHA1');
				var pem = fs.readFileSync(__dirname + '/pem/privatekey.pem');
				var ky = pem.toString('ascii');
				sign.update(base_string, 'UTF-8');
				return sign.sign(ky, 'base64');
			};
			break;

**Comment by paulrutter** [comment]
Maybe we could add this alongside my existing pull request: https://github.com/ddo/oauth-1.0a/pull/36?
@ddo Are you going to merge PR's or not? If not, how can we proceed?
There is a risk the repository will be forked, and implementations are going to differ accross branches.

**Comment by ddo** [comment]
@paulrutter soon

**Comment by ddo** [comment]
just release new major version of oauth-1.0a: 2.0.0 read the changelog here
https://github.com/ddo/oauth-1.0a/releases/tag/2.0.0

**Comment by paulrutter** [comment]
Cool, thanks :)
