### ISSUE TITLE
How to: callback URL

### ISSUE THREAD

**Issue by chuckdries** [ddo/oauth-1.0a#41]
I'm using oauth-1.0a with wordpress and I just want to know how to get oauth.authorize to include a callback URL. Do I define it in the request object that I pass to oauth.authorize()? What parameters, then, do I use?

[The Oauth Bible](http://oauthbible.com) says that for 3 legged authorization callback urls can be used, so it's not a wordpress specific thing.

**Comment by ddo** [comment]
https://github.com/ddo/oauth-1.0a/blob/master/README.md#authorize-options-

example

https://github.com/ddo/oauth-1.0a/blob/0dea46b79c402ba9484e1960bc39830a823c6d24/test/services/linkedin.js#L24

**Comment by chuckdries** [comment]
Thanks!
