### ISSUE TITLE
Base string incorrect for array type GET query string

### ISSUE THREAD

**Issue by robmacecs** [ddo/oauth-1.0a#49]
It seems that array type GET query strings aren't quite supported. 

e.g.

```
// request_data.data
{ 
  filter: [ { attribute: 'updated_at', from: '2017-05-10 00:00:00' } ],
  limit: 100,
  page: 1 
}
```
If you url encode this with something like qs, then you would get 
```
filter%5B0%5D%5Battribute%5D=updated_at&filter%5B0%5D%5Bfrom%5D=2017-05-10%2000%3A00%3A00&limit=100&page=1
```
or in other words 
```
filter[0][attribute]=updated_at&filter[0][from]=2017-05-10 00:00:00&limit=100&page=1
```
Which is a valid query string. 

However, when the module is getting the Base string from this, the parameter string comes out like so
```
filter%3D%255Bobject%2520Object%255D%26filter%25255B0%25255D%25255Battribute%25255D%3Dupdated_at%26filter%25255B0%25255D%25255Bfrom%25255D%3D2017-05-10%252000%253A00%253A00%26limit%3D100%26page%3D1
```
Which decodes to 
```
filter=[object Object]&filter[0][attribute]=updated_at&filter[0][from]=2017-05-10 00:00:00&limit=100&page=1
```
So as you can see it is _nearly_ correct but the `filter=[object Object]&` breaks it.
Is there some other way I should be passing in the filter array to make this work like qs?
If I omit the `filter` parameter, then the signature works fine with the other params.

Hopefully I've explained myself well enough, thanks

If you are wondering, the filters in this format are expected by Magento's REST API 
http://devdocs.magento.com/guides/m1x/api/rest/get_filters.html

**Comment by robmacecs** [comment]
Also just in case anyone was wondering, I've removed the `oauth_` params from the parameter string, but they _were_ there in the correct place

**Comment by ddo** [comment]
will check

**Comment by robmacecs** [comment]
So I think there are 2 things going on. Firstly, there's the issue that when `percentEncodeData` doesn't accept an array of objects. So that's where this comes from 
```
{ key: 'filter', value: [ '%5Bobject%20Object%5D' ] }
```
The other issue is almost the opposite, in that `deParam` doesn't support decoding arrays from the url parameter string. Which means that when the objects are merged, you end up with all 3 like so
```
{ key: 'filter', value: [ '%5Bobject%20Object%5D' ] },
{ key: 'filter%255B0%255D%255Battribute%255D', value: 'updated_at' },
{ key: 'filter%255B0%255D%255Bfrom%255D', value: '2017-05-10%2000%3A00%3A00' },
```

**Comment by ddo** [comment]
@asharpe-squiz

**Comment by robmacecs** [comment]
Hi again,
So after more playing around, I figured out I could get this to work by using `qs` to do some of the encoding/decoding. I don't know whether you would prefer to add `qs` as a dependency or if you'd rather replicate this functionality in your own module?
Do you have any contribution guidelines? 
Thanks

**Comment by ddo** [comment]
hi,

all the PR should pass the tests, if you can't test on local then you just create a pull request to trigger the semaphoreci.

and also add the new test cases in ``/test``

ty

**Comment by paulrutter** [comment]
I didn't see this issue earlier, but it looks a lot like the issue i encountered: having multiple duplicate parameters in the querystring doesn't result in a valid signature.
See my pull request: https://github.com/ddo/oauth-1.0a/pull/58
Haven't tested it, but it might fix your issue as well?

**Comment by ddo** [comment]
@robmacecs please help to check

**Comment by paulrutter** [comment]
Ah, looking again i see you issue is about the body parameters (mine was about querystring parameters), so this is probably not fixed by my pull request.

**Comment by dinoboff** [comment]
IMHO, `OAuth-1.0a` is a low level library and should not try to encode complex object; there's many way to encode them and there's no way to ensure the http client encoding will match `OAuth-1.0a` one. The solution would be to encode the data first, or let the http client encode it, and provide the encoded data to `OAuth-1.0a`. `OAuth-1.0a` would have to parse it like it parses the query string.

An alternative would be to add a `data_encoder` option.

**Comment by ddo** [comment]
for complicated object data, you should turn it to json string JSON.stringify(data) then send it as a string.
