### ISSUE TITLE
Doesn't seem to handle "realm" properly.

### ISSUE THREAD

**Issue by jt55401** [ddo/oauth-1.0a#50]
The method we're calling requires the use of the Oauth realm, and we tried specifying that in the request_data.data map we sent do the oauth.authorize method. This "almost worked", but not quite.

Issues:
1) The realm was included in the string to sign, but that should not be so.
2) The realm was properly included in the OAuth header string, but it was last (per alphabetical order) but realm is required to be first in the header.

We worked around for now by NOT specifying the realm in the data, and instead, manually adding it before use...

```
var request_data = {    
    url: 'http://www.example.com',
    method: 'GET'
};

// generate the auth header WITHOUT any realm.
var headers = oauth.toHeader(oauth.authorize(request_data, token));
// manually add the realm after the fact:
headers.Authorization = headers.Authorization.replace("OAuth ", 'OAuth realm="12345",');

request({    
    url: request_data.url,
    method: request_data.method,
    headers: headers
}, function(error, response, body) {    
    console.log(body);
});
```

**Comment by ddo** [comment]
working on it

**Comment by ddo** [comment]
please checkout the newest code and test with your oauth service. the new options is ``realm``, ex:

```js
var oauth = new OAuth({
    consumer: {
        key: "batch-dbc2cd8c-6ca8-463b-96e2-6d8683eac6fd",
        secret: "4S4Rvm25CJZWv7HBg5HOhhlRTBSZ7npl"
    },
    realm: "https://ddo.me/",
    signature_method: 'HMAC-SHA1',
    hash_function: hash_function_SHA1
});
```
i will public on npm after your tests. ty

**Comment by jt55401** [comment]
Will do later today, thanks!

**Comment by RobGriggs** [comment]
Hi there @ddo,

I've been working @jt55401. He figured out the workaround when I was unable implement the library using a realm. I pulled the latest code into the my project and reconfigured my connection script to follow the format that you outlined above. 

Connection was successful using the new realm option!

![capture](https://user-images.githubusercontent.com/2215578/26888920-1ee5b504-4b72-11e7-8cb4-25809f94d7c2.PNG)

Thanks all.

**Comment by ddo** [comment]
does your realm contain any non alphabet characters such as ``/``, ``:``

**Comment by jt55401** [comment]
in our case, no.

**Comment by ddo** [comment]
so everything ok?

**Comment by jt55401** [comment]
Yes, works great now!

**Comment by ddo** [comment]
ty

https://github.com/ddo/oauth-1.0a/releases/tag/2.2.0
