### ISSUE TITLE
Update from 2.1.0 to 2.1.1 breaks signature

### ISSUE THREAD

**Issue by francescosalvi** [ddo/oauth-1.0a#55]
Hello
first of all, thanks for the useful library.
Since I updated the dependency in my project (integrates with the Beatport API, 3-legged) and it passed from 2.0.0 to 2.2.0, I get "Invalid OAuth signature. Expected value ..." when performing a Request Token request. 

Since nothing has changed in the code/environment/configuration, I was wondering if you could give me any hint about what major changes that were introduced in this version that might need my attention

The affected request uses POST and .toHeader()

Thank you!

**Comment by ddo** [comment]
pls take a look on some minor changes here: https://github.com/ddo/oauth-1.0a/releases

**Comment by francescosalvi** [comment]
I updated the issue title since after more accurate tests I noticed that compatibility is maintained until 2.1.1 (excluded),  which introduces "preserve sorted parameters"

I will try to debug around the diff-ed parts of the code

Thanks

**Comment by francescosalvi** [comment]
Hello
I think I found the problem:

When debugging the output from `OAuth.prototype.getParameterString`, here are the compared results:

In 2.1.0

	format=json&
	oauth_callback=http%3A%2F%2Flocalhost%3A5000%2FaccessToken&
	oauth_consumer_key=...
	oauth_nonce=wF3Mmg2G4qWZk4ve20mJSwN116eM87EJ&
	oauth_signature_method=HMAC-SHA1&
	oauth_timestamp=1501576821&
	oauth_version=1.0
	
In >= 2.1.1

    // same, but at the end it's:
	oauth_version=1.0&
	undefined=undefined

The reason for this is that in the newer versions you are returning an Array from `OAuth.prototype.sortObject`, which *in my case/project* happens to have an extended prototype with a property named "move"

	Array.prototype.move = function(from, to) { this.splice(to, 0, this.splice(from, 1)[0]); };
	var arr = [];
	for (i in arr) {console.log(i);}
	
	>>> move

This property gets then translated into key = undefined, value = undefined; you check against the existence of value @148 but you still print it out @162, even if undefined

To fix the problem (I can assume that other users might be using "extended" Arrays in their projects at some point) one possible fix is:

	-    for(var i in base_string_data) {
	+    for(let i = 0; i <  base_string_data.length; i++) {

Or Array.forEach (ES5)

	-    for(var i in base_string_data) {
	+    base_string_data.forEach(function(elem, i, arr) {
	+        var key = elem.key;
	+        var value = elem.value;

**Comment by ddo** [comment]
so the problem only happens when you modify the array prototype right? ex: ``Array.prototype.move``

**Comment by francescosalvi** [comment]
exactly

**Comment by ddo** [comment]
a PR would be great

**Comment by francescosalvi** [comment]
ok then!

**Comment by ddo** [comment]
i refer
```js
for(let i = 0; i <  base_string_data.length; i++) {
```
ty

**Comment by francescosalvi** [comment]
this is also a working solution

```javascript
     for(var i in base_string_data) {
+        if (!base_string_data.hasOwnProperty(i)) {continue;}
```

still prefer the "classic" for loop?

**Comment by ddo** [comment]
yes classic loop kinda easier to understand. ``for in`` should be for object properties iterate

**Comment by ddo** [comment]
#56
