### ISSUE TITLE
better README?

### ISSUE THREAD

**Issue by ddo** [ddo/oauth-1.0a#61]
any contribution would be appreciated

**Comment by ddo** [comment]
refactor examples kinda what we need right now i guess

**Comment by adnanebrahimi** [comment]
realm parameter in options needed for constructor ... take 2 hours to find it why the constructor throw me an error. Please update  README

**Comment by ddo** [comment]
@adnanebrahimi i have no issue like that. there is no realm in my test cases. Are you using js?

**Comment by adnanebrahimi** [comment]
Yes I'm using js file in  Angular but i install it with npm..

**Comment by ddo** [comment]
#76
