### ISSUE TITLE
Query string parameters are added to final 'oauth_data' object

### ISSUE THREAD

**Issue by gear54rus** [ddo/oauth-1.0a#70]
This line: https://i.imgur.com/RBYbFRl.png

Modifies both `request` and `oauth_data`. Is this intended? I realize that QS parameters needs to be used when computing base string, but it shouldn't end up in header, should it?

It ends up in header (when using `toHeader`) because authorize returns the modified `oauth_data`: https://i.imgur.com/cTa72JI.png

Is this intended? Shouldn't `oauth_data` be copied before using `mergeObject`?

**Comment by gear54rus** [comment]
Poking around the code it generally feels that all possible parameters are mixed together and written everywhere possible (stuff from `options.data` like `oauth_version` will end up hashed as part of body when it isn't). This breaks some services. Am I missing something?

**Comment by ddo** [comment]
any custom parameters can be pass as oauth data fyi
