### ISSUE TITLE
Fix typings

### ISSUE THREAD

**Issue by maximelkin** [ddo/oauth-1.0a#71]
Make realm parameter in options optional.

**Comment by ddo** [comment]
isn't it?

**Comment by Nephrited** [comment]
@ddo It is not!

**Comment by maximelkin** [comment]
Should fix also affect this line?
https://github.com/ddo/oauth-1.0a/blob/master/oauth-1.0a.d.ts#L16

**Comment by ddo** [comment]
well i think ``js`` is optional. but ``ts`` is not. PRs are welcome, i have no idea about ``ts``
