### ISSUE TITLE
Same oauth_nonce, add a way to seed the getNonce function

### ISSUE THREAD

**Issue by miguelcrespo** [ddo/oauth-1.0a#72]
Hi, my team is currently experiencing an unexpected behavior when bots try to index our page, this is because some bots always generate the same value when you call:
`Math.random();`

So when this library tries to generate an oauth_nonce It will always be the same because this line use the number generated by Math.random

`        result += word_characters[parseInt(Math.random() * word_characters.length, 10)];
`

Maybe we should add a way to seed the randomness of this function? What do you think?

**Comment by ddo** [comment]
i wonder how ``Math.random()`` can return same result? did you modify ``Math.random``?

**Comment by MiguelCrespo** [comment]
No, that's because when the code run on the Google's servers (To be indexed in Google search), Math.random() is going to be deterministic and It's always going to return the same result, you can refer this for more info:
http://www.tomanthony.co.uk/blog/googlebot-javascript-random/

**Comment by ddo** [comment]
please test this random method

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

so i may try this one

**Comment by MiguelCrespo** [comment]
Hi, the crypto.getRandomValues didn't work, It also created the same number each time, but I fixed it by adding a timestamp at the end of the oauth_nonce.

Thank you.

**Comment by ddo** [comment]
ty will try to improve the random function

**Comment by ddo** [comment]
for some clouds or serverless services ``Math.random`` could return the same fyi

**Comment by LinsonAlfred** [comment]
> for some clouds or serverless services `Math.random` could return the same fyi

So isn't good idea to use this package for AWS lambdas?
