### ISSUE TITLE
Easy-Jquery ETA?

### ISSUE THREAD

**Issue by johnyradio** [ddo/oauth-1.0a#73]
Thx for code!

Any ETA on the version listed as: 

> Want easier? Take a look: **jquery: soon**
[Here](https://github.com/ddo/oauth-1.0a), under **"Notes"**

I'm developing a new project, and just wondering if i should wait for it.

**Comment by ddo** [comment]
Sorry it's outdated. I will update the README later. thanks for info

**Comment by johnyradio** [comment]
Hi, you mean the "easier" jQuery method is now available? Thx

**Comment by ddo** [comment]
No. That's TODO was abandoned
