### ISSUE TITLE
Invalid signature issue - 401 error

### ISSUE THREAD

**Issue by KahtiD** [ddo/oauth-1.0a#74]
HI, I'm fairly new to coding so forgive my ignorance if this is not supposed to go here. But I am stuck on how to rectify this issue considering on postman I can get back data but I guess I am not writing my code properly? Any help. 

This is my code: 
```
componentDidMount() {
  const oauth = OAuth({
    consumer: {
      key: 'XXXXX',
      secret: 'XXXXX',
      signature_method: 'HMAC-SHA1',
      hash_function(base_string, key) {
        return crypto.createHmac('sha1', key).update(base_string).digest('base64');
      }
    },
  });

  const request_data = {
    url: 'http://localhost:8888/wp-json/wc/v2/products/28/variations',
    method: 'GET',
  };

  const token = {
    key: 'XXXXX',
    secret: 'XXXXX',
  };

  fetch(request_data.url, {
    method: request_data.method,
    headers: oauth.toHeader(oauth.authorize(request_data, token))
  })
    .then(response => response.json())
    .then(response => {
      this.setState({
         products: response
      })
   })
}
```

**Comment by ddo** [comment]
hi. pls try
https://github.com/ddo/oauth-1.0a/issues/35

**Comment by KahtiD** [comment]
Thank you I realised the position of my `signature method` and `hash_function` where in the wrong object!! much appreciated

**Comment by KumarSyscon** [comment]
Hi there,
I am getting 401 error sometimes. It does work 5 out of 10 times. It gives 401 error when oauth_signature contains the character '+'.
const auth = oauth.authorize(request_data);
    let headers = new HttpHeaders();
    headers = headers.set('Authorization', 'OAuth oauth_consumer_key="' + auth.oauth_consumer_key
      + '", oauth_nonce="' + auth.oauth_nonce
      + '", oauth_signature="' + auth.oauth_signature
      + '", oauth_signature_method="HMAC-SHA1", oauth_timestamp="' + auth.oauth_timestamp
      + '", oauth_version="1.0"').set('content-type', 'text/plain').set('accept', 'text/plain');
    console.log(headers);
    this.http.get(request_data.url, { headers: headers },
    ).subscribe(res => console.log(res));
