### ISSUE TITLE
401 error - invalid oauth signature

### ISSUE THREAD

**Issue by KumarSyscon** [ddo/oauth-1.0a#75]
Hi there I am getting 401 errors sometimes when I use the following code.
The error in the log is InvalidSignatureException.  I have also found that whenever the signature has + in it, then I am getting this error. Please let me know if the code below is not correct.

import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

const createHmac = require('create-hmac');
const OAuth = require('oauth-1.0a');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  constructor(private http: HttpClient) { }

  ngOnInit() {
    const oauth = OAuth({
      consumer: {
        key: 'XXXXX',
	  secret: 'XXXXXX'},
      signature_method: 'HMAC-SHA1',
      hash_function(base_string, key) {
        return createHmac('sha1', key).update(base_string).digest('base64');
      }
    });

    const request_data = {
      url: 'XXXXXX',
      method: 'GET',
    };

    const auth = oauth.authorize(request_data);
    let headers = new HttpHeaders();
    headers = headers.set('Authorization', 'OAuth oauth_consumer_key="' + auth.oauth_consumer_key
      + '", oauth_nonce="' + auth.oauth_nonce
      + '", oauth_signature="' + auth.oauth_signature
      + '", oauth_signature_method="HMAC-SHA1", oauth_timestamp="' + auth.oauth_timestamp
      + '", oauth_version="1.0"').set('content-type', 'text/plain').set('accept', 'text/plain');
    console.log(headers);
    this.http.get(request_data.url, { headers: headers },
    ).subscribe(res => console.log(res));
  }
}

**Comment by KumarSyscon** [comment]
I am getting the 401 error for all requests now -         
        const oauth_data = oauth.authorize(request_data, token)
	const oauth_header = oauth.toHeader(oauth_data);
	let headers = new HttpHeaders();
	headers = headers.set('Authorization', oauth_header.Authorization);

**Comment by ddo** [comment]
I think you are missing some steps
Please make sure you understand and do step by step full-flow of the oauth.
Please check here: http://oauthbible.com/

**Comment by KumarSyscon** [comment]
This is my current code  - 

import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

const createHmac = require('create-hmac');
const OAuth = require('oauth-1.0a');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  constructor(private http: HttpClient) { }

  ngOnInit() {
    const oauth = OAuth({
      consumer: {
        key: 'XXX',
	  secret: 'XXXX'},
      signature_method: 'HMAC-SHA1',
      hash_function(base_string, key) {
        return createHmac('sha1', key).update(base_string).digest('base64');
      }
    });
	
	const token = {
    key: 'XXX',
    secret: 'XXX'
  };

    const request_data = {
      url: 'XXXXX',
      method: 'GET'
    };

	const oauth_data = oauth.authorize(request_data, token)
	const oauth_header = oauth.toHeader(oauth_data);
	let headers = new HttpHeaders();
	headers = headers.set('Authorization', oauth_header.Authorization);  
    console.log(headers);
    this.http.get(request_data.url, { headers: headers },
    ).subscribe(res => console.log(res));
  }
}

**Comment by sirluis** [comment]
@KumarSyscon check the url, don't forget to include http:///https://.
