### ISSUE TITLE
oauth_verifier is missing

### ISSUE THREAD

**Issue by sergio-alifano** [ddo/oauth-1.0a#78]
I'm not sure if this library is supposed to work only for the first leg of the Oauth1.0 flow (something like "/.../oauth1/Request"), but after the consumer receives the temporary tokens and being redirected to the provider login page, it receives back an oauth_token and **oauth_verifier**. 
The **oauth_verifier** must be part of the last request (something like "/...oauth1/Access") in order to receive the token and token_secret used to access protected resources. 

I had to modify the library to include this **oauth_verifier** token for the third leg of the Oauth1 flow to make it work. 

Anybody else in my situation? Should I make a PR?

**Comment by ddo** [comment]
just set ``oauth_verifier`` as normal body data
example:

https://github.com/ddo/oauth-1.0a/blob/08f54922f4ac2bba527111583a8bb49661cec704/test/services/flickr.js#L96-L133

**Comment by pszabop** [comment]
> just set oauth_verifier as normal body data

The oauth provider I'm using wants the verifier in the Authorization header, not in the body, so I don't think this method is going to work.  the `oauth.toHeader()` in particular will not work.

**Comment by pszabop** [comment]
the solution is nonintuitive, but it works.  Something in the code takes anything that starts with `oauth` in the `data` field and adds it to the Authentication header as well as including it in the signature.  After calling `oauth.toHeader` I got the `oauth_verifier` field in my Authorization header.

i.e., the following works (from a tape test, easier to read than mocha)

```
  const requestData = {
    url: requestTokenUrl,
    method: 'POST',
    data: {
      oauth_verifier: 'the_verifier_value'
    },
  }
  const req = axios.create({
    baseURL: requestTokenUrl,
    timeout: 20000,
    headers: oauth.toHeader(oauth.authorize(requestData, {
      key: 'the_request_key',
      secret: 'the_request_key_secret',
    })),
    validateStatus: function(status) {
      return status <= 405;
    },
  });

```
which resulted in authorization headers:

```
Authorization: 'OAuth oauth_consumer_key="the_consumer_key", oauth_nonce="Z4P12UcQAPbVXUgCYu6j5hMYgpXUbjy8", oauth_signature="vaonMXVuqzPh8pZCPL5fMAUnnRQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1589736880", oauth_token="the_request_token", oauth_verifier="the_verifier_value", oauth_version="1.0"'
```

And with the correct values my oauth 1.0 provider was happy.

**Comment by phuocantd** [comment]
> the solution is nonintuitive, but it works. Something in the code takes anything that starts with `oauth` in the `data` field and adds it to the Authentication header as well as including it in the signature. After calling `oauth.toHeader` I got the `oauth_verifier` field in my Authorization header.
> 
> i.e., the following works (from a tape test, easier to read than mocha)
> 
> ```
>   const requestData = {
>     url: requestTokenUrl,
>     method: 'POST',
>     data: {
>       oauth_verifier: 'the_verifier_value'
>     },
>   }
>   const req = axios.create({
>     baseURL: requestTokenUrl,
>     timeout: 20000,
>     headers: oauth.toHeader(oauth.authorize(requestData, {
>       key: 'the_request_key',
>       secret: 'the_request_key_secret',
>     })),
>     validateStatus: function(status) {
>       return status <= 405;
>     },
>   });
> ```
> 
> which resulted in authorization headers:
> 
> ```
> Authorization: 'OAuth oauth_consumer_key="the_consumer_key", oauth_nonce="Z4P12UcQAPbVXUgCYu6j5hMYgpXUbjy8", oauth_signature="vaonMXVuqzPh8pZCPL5fMAUnnRQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1589736880", oauth_token="the_request_token", oauth_verifier="the_verifier_value", oauth_version="1.0"'
> ```
> 
> And with the correct values my oauth 1.0 provider was happy.

I using it and request return message 401 Invalid signature for signature method HMAC-SHA1
