### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by stupax** [ddo/oauth-1.0a#80]
Anyone getting this? TypeError: Cannot read property 'toUpperCase' of undefined. Not sure what i am doing wrong.  my code - 

request({
    url: hook.params.query.url,
    method: hook.params.query.method,
    form: modelData.data,
    headers: oauth.toHeader(oauth.authorize(modelData.data, token))
  }, function(error, response, body) {
    // Process your data here
  });

**Comment by stupax** [comment]
got it working

**Comment by CapitanRedBeard** [comment]
@stupax What was your fix here? Running into the same error

**Comment by jaschaio** [comment]
Me too. @stupax what was your mistake?

**Comment by jaschaio** [comment]
@CapitanRedBeard I found my mistake. The `request` passed to `oauth.authorize` was undefined:

```javaScript
const requestData = {
    url: `https://${ oauthProviders[ provider ].authorizeUri }`,
    method: 'POST',
    qs: {
        oauth_callback: `${ config.origins.auth }/oauth/${ provider }/`,
        x_auth_access_type: 'read'
    }
};

var response = await request( {
    method: requestData.method,
    uri: requestData.url,
    qs: requestData.qs,
    headers: oauth.toHeader( oauth.authorize( request ) ) // Should reference requestData instead of request
} );
```

Second to last line should reference `requestData` and not `request`.
