### ISSUE TITLE
Signature Not Handling Complex Object Structure

### ISSUE THREAD

**Issue by zarni-abacus** [ddo/oauth-1.0a#82]
Hi,

I am integrating with an API which uses oauth1 authentication.
I am able to perform get and post request.
However when I try to include Customer object in my below payload, the api reject with Authorization error probably due to signature issue.
I observe that authorize function returns empty Customer like &Customer=&

const visitDate = moment().tz('Australia/Sydney').add(2, 'h').format('YYYY-MM-DDTHH:mm:ss');            
            const bookingInfo = {
                Covers: 1,                
                Duration: 60,                
                Status: 1,
                Tables:24102,
                VisitDateTime: visitDate,
                Customer: {                    
                    "Email": "zarni@mail.co",
                    "Title": "Mr",
                    "FirstName": "Zarni",
                    "Surname": "Aung",                    
                    "MobileNumber": "00112233"
                }                         
            };
Would you encounter such issue before?

**Comment by ddo** [comment]
you should turn it to json string ``JSON.stringify(bookingInfo)`` 1st then send it as data.
