### ISSUE TITLE
TypeScript definitions should not have implicit any

### ISSUE THREAD

**Issue by kjellmorten** [ddo/oauth-1.0a#84]
Thanks for create this module and for including a `d.ts` file!

The definition for `BodyHashFunction` is missing types for its arguments, though. This causes `tsc` to complain, when `noImplicitAny` is turned on.

This should be easy to fix:
```
export type BodyHashFunction = (base_string: string, key: string) => string
```

I would be happy to provide a PR. Just let me know.

Thanks again!

**Comment by ddo** [comment]
#77 is this enough?

**Comment by kjellmorten** [comment]
Yes, this is great. Thanks!
